## DATATHON NOTEBOOK

Prompt: Analyzing the relations between call attributes and customer call reasons within the IVR (Interactive Voice Response) system with an
emphasis on calls that the IVR could not handle (i.e., floor calls).

Deliverables:
* Adding functionality
* Preventing a re-call
* Providng the caller a more effective channel of choice


Points of Interest:
* Calls with [resolved] status of 'floor'
* Re-calls: Same serial number AND same day

In [4]:
import pandas as pd

In [5]:
df1 = pd.read_csv("./data/file_3_Mar18_Output_1.csv")

In [6]:
df2 = pd.read_csv("./data/file_4_Mar18_Output_1.csv")

In [7]:
df = pd.concat([df1, df2], ignore_index=True)

In [8]:
df.duplicated().value_counts()

False    1798798
Name: count, dtype: int64

## PREPROCESSING

##### Adding a column with more descriptive reason

In [9]:
reason_dict = {
    "AA":"Activation",
    "AG":"Transferred from agent",
    "AL":"Account lookup",
    "AP":"Address phone change",
    "AR":"APR Information",
    "AS":"Application status",
    "AT":"Account transactions",
    "AU":"Non account specific info",
    "BA":"Account Summary",
    "Ba":"Skip balance summary",
    "BL":"Balance letter",
    "CA":"Close account",
    "CB":"Credit balance refund",
    "CC":"Recovery",
    "CD":"Change due date",
    "CS":"Claim Status",
    "CT":"CIT Change in Terms",
    "CX":"360 Servicing",
    "DA":"What is DA",
    "DB":"Default Balance",
    "DE":"Deceased Notification",
    "DP":"Disputes",
    "DR":"Decline Sale",
    "DS":"Disputes",
    "eA":"eService Assistance",
    "eB":"eService Bill",
    "EB":"Explain Benefit",
    "eL":"eService Login",
    "eP":"eService Password",
    "eR":"eService Registration",
    "ER":"eService Registration",
    "eS":"eService Security",
    "eY":"eService Online Payment",
    "FB":"Unfreeze account",
    "FD":"Fraud detect",
    "FI":"Fraud -instalink ",
    "FM":"manage fraud - L/S with fraud",
    "GA":"Get account number",
    "HI":"HRT - Instalink",
    "iA":"Cash access",
    "IA":"Identification and authentication",
    "iB":"Credit bureau inquiry",
    "iC":"Commercial account",
    "IC":"Credit increase",
    "IE":"Insurance enrollment",
    "iF":"Membership Fee",
    "iL":"Refer customer to store",
    "iM":"Membership club",
    "iO":"Internet Order",
    "iP":"Payment allocation",
    "IR":"Interest rate",
    "iR":"Rewards",
    "iS":"StoneBridge insurance",
    "iT":"Travel club",
    "IV":"Transferred from IVR",
    "LC":"Live chat",
    "LM":"List Transaction SMS",
    "LS":"Report lost stolen",
    "Ls":"Report lost stolen",
    "LW":"online lockout",
    "m":"menu non-standard",
    "ma":"menu accounts",
    "me":"menu eService",
    "MF":"Negative ANI",
    "mm":"main menu",
    "mn":"menu upfront",
    "mo":"more menu options",
    "mp":"menu payment",
    "MP":"Missing payment",
    "Mr":"SMS eService link offer",
    "MR":"SMS Account Summary",
    "mt":"pre transfer menu",
    "nl":"NLU menu How may I help you",
    "NU":"Null",
    "OB":"OB IB Prediction",
    "OC":"OB IB Prediction for any",
    "OI":"Outbound inbound",
    "OO":"Opt out of upgrade",
    "OR":"OB IB Prediction for Reuben",
    "OV":"OB IB Prediction for Vail",
    "PA":"Payment address",
    "PC":"Cancel payment ",
    "Pd":"Promo balance",
    "PF":"Payment Information",
    "PH":"Phone change",
    "PI":"Proactive Income",
    "PO":"New Policy",
    "PP":"PBP Predictive",
    "PR":"Privacy",
    "PS":"Payment sent",
    "PT":"PBP Request",
    "PV":"Privacy",
    "PX":"Prox",
    "Py":"Pending payment info",
    "RC":"Replacement card",
    "RI":"Return Payment ",
    "RP":"PIN Request",
    "RS":"Global router",
    "RV":"Recovery",
    "SA":"Sale authorization",
    "SP":"Summary payment",
    "SR":"Statement reprint",
    "ss":"Transfer",
    "ST":"SMS Transfer Router",
    "Ta":"SMS Activation",
    "TA":"SMS Account Summary",
    "TB":"SMS Lost Stolen - New card",
    "TC":"SMS CLI",
    "TD":"SMS Close account",
    "Te":"Register my account static URL",
    "TE":"Register my account tokenized",
    "Tf":"SMS Flip Activation",
    "TF":"SMS Flip Activation",
    "TL":"SMS Lost Stolen",
    "TN":"SMS Replacement Card",
    "TP":"SMS Payment Sent",
    "TR":"Transfer",
    "TS":"SMS Account Summary",
    "TU":"SMS Upfront Router",
    "UP":"Agree to upgrade",
    "VP":"Mobile Pay",
    "VR":"Mobile Registrations",
    "WA":"Late fee waiver",
    "wa":"Request waiver",
    "rP":"Personal or business",
    "P1":"payment request  (3rd party system)",
    "P2":"Details about recovery acct",
    "S1":"Charge off paid in full letter",
    "S2":"1099C information",
    "S3":"Account questions",
    "P3":"CCCS and debt settlement option",
    "C1":"CCCS info",
    "C2":"Debt Settlement companies ",
    "P4":"Report a Bankruptcy",
    "P5":"Report disputed charge off",
    "P6":"Report Fraudulent charge off",
    "rT":"Third party",
    "T1":"Customer's permission",
    "A1":"Third party payment",
    "A2":"Third party other questions",
    "T2":"No customer permission",
    "T3":"Deceased notification",
    "D1":"Request deceased notice SMS",
    "D2":"Select website information",
    "D3":"Discuss deceased acct",
    "D4":"What is D4 in Recovery IVR",
    "FR":"Fraud Block Removal",
    "PD":"Past due",
    "OL":"Over Limit",
    "NO":"No OTB",
    "XR":"Expediated registration",
    "VA":"Vague address",
    "mP":"Minimum Payment disambiguation",
    "AM":"Uttered Amazon in NLU"
}

In [10]:
def reason_description(row):
    if row.reason in reason_dict.keys():
        return reason_dict[row.reason]
    else:
        return "UNABLE TO PARSE REASON"

In [11]:
df["Reason Description"] = df.apply(reason_description, axis=1)

### PLAYGROUND ###

In [12]:
copy = df.copy()
copy.shape

(1798798, 25)

In [26]:
copy

,timestamp_call_key,retailer_code,serial,reason,mos,resolved,no_of_accounts_with_syf_13_march,account_balance_13_march,delinquency_history_13_march,account_open_date_13_march,...,no_of_accounts_with_syf_18_march,account_balance_18_march,delinquency_history_18_march,account_open_date_18_march,account_status_18_march,card_activation_status_18_march,eservice_ind_18_march,ebill_enrolled_status_18_march,auto_pay_enrolled_status_18_march,Reason Description
0,240315173250 DAL1OA3M,D,10010009499,PP,IA PP TR,resolved,1.0,NaN,[00],5/19/2013,...,1.0,NaN,[00],5/19/2013,NaN,0,1,E,0,PBP Predictive
1,240315124742 DAL15XHK,E,10006021998,BA,IA BA TS nl TR,floor,2.0,143.28,[00],9/22/2003,...,2.0,143.28,[00],9/22/2003,NaN,0,1,E,0,Account Summary
2,240317114237 DAL3BLK6,J,10016007830,PT,IA AA BA MR nl PT TR,resolved,12.0,0.00,[00],9/4/2017,...,12.0,0.00,[00],9/4/2017,NaN,8,0,,0,PBP Request
3,240314120849 PHX6PL4U,E,10008003199,BA,IA BA,resolved,2.0,44.98,[00],2/7/2024,...,2.0,-6.32,[00],2/7/2024,NaN,0,0,L,0,Account Summary
4,240314145902 DAL68RYS,I,10013002037,BA,IA BA TS nl mm TR,floor,6.0,7.00,[00],1/2/2022,...,6.0,7.00,[00],1/2/2022,NaN,0,1,,0,Account Summary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1798793,240314120118 DAL2JPAQ,i,20012001463,BA,IA BA TA nl,resolved,14.0,1314.94,[00],2/8/2022,...,14.0,1314.94,[00],2/8/2022,NaN,0,0,,0,Account Summary
1798794,240314120336 DAL4K2UN,i,20012001463,BA,IA BA,resolved,14.0,1314.94,[00],2/8/2022,...,14.0,1314.94,[00],2/8/2022,NaN,0,0,,0,Account Summary
1798795,240316190932 PHX2S13U,a,20001160188,PP,IA PP TR,resolved,7.0,35.66,[00],8/24/2023,...,7.0,35.66,[00],8/24/2023,NaN,0,0,,0,PBP Predictive
1798796,240317213341 PHX35A2C,d,20010020211,FD,IA IA TR,floor,8.0,386.63,[00],5/15/2019,...,8.0,386.63,[00],5/15/2019,A,0,1,L,0,Fraud detect
1798797,240316115154 PHX3G20E,d,20010013226,LS,IA AA BA TS nl LS nl nl LS TR,floor,6.0,261.74,[00],11/18/2018,...,6.0,261.74,[00],11/18/2018,NaN,8,1,E,0,Report lost stolen

In [13]:
copy.columns.tolist()

['timestamp_call_key',
 'retailer_code',
 'serial',
 'reason',
 'mos',
 'resolved',
 'no_of_accounts_with_syf_13_march',
 'account_balance_13_march',
 'delinquency_history_13_march',
 'account_open_date_13_march',
 'account_status_13_march',
 'card_activation_status_13_march',
 'eservice_ind_13_march',
 'ebill_enrolled_status_13_march',
 'auto_pay_enrolled_status_13_march',
 'no_of_accounts_with_syf_18_march',
 'account_balance_18_march',
 'delinquency_history_18_march',
 'account_open_date_18_march',
 'account_status_18_march',
 'card_activation_status_18_march',
 'eservice_ind_18_march',
 'ebill_enrolled_status_18_march',
 'auto_pay_enrolled_status_18_march',
 'Reason Description']

In [14]:
copy['Reason Description'].value_counts().nlargest(35)/1798798*100

Reason Description
PBP Predictive                       37.709293
Account Summary                      31.484969
PBP Request                          12.318393
Account transactions                  5.081393
Activation                            3.049870
CIT Change in Terms                   1.322883
Request waiver                        0.794753
Report lost stolen                    0.765567
Fraud detect                          0.723094
Live chat                             0.560152
Credit increase                       0.495386
Identification and authentication     0.423449
menu payment                          0.423283
Promo balance                         0.396098
Disputes                              0.385257
Address phone change                  0.374083
Close account                         0.329109
Late fee waiver                       0.272960
manage fraud - L/S with fraud         0.264343
Replacement card                      0.232655
menu upfront                          0.223927
Recovery                              0.208806
Credit balance refund                 0.205359
Proactive Income                      0.191628
Summary payment                       0.149767
Payment address                       0.144986
PIN Request                           0.135813
Rewards                               0.120191
menu eService                         0.119524
Refer customer to store               0.115132
Get account number                    0.113520
Payment sent                          0.098510
eService Login                        0.091283
Decline Sale                          0.084723
Missing payment                       0.083556
Name: count, dtype: float64

In [15]:
cFloor = copy[copy['resolved'] == 'floor']
cFloor.shape

(366217, 25)

In [16]:
cFloor['Reason Description'].value_counts().nlargest(50)/366217*100

Reason Description
Account Summary                      43.251406
PBP Predictive                        9.164512
CIT Change in Terms                   6.302820
PBP Request                           4.999495
Activation                            4.120235
Request waiver                        3.617527
Fraud detect                          3.406177
Report lost stolen                    2.589175
Account transactions                  2.372091
Live chat                             2.070357
Disputes                              1.864468
menu payment                          1.481635
Promo balance                         1.327082
Address phone change                  1.239975
manage fraud - L/S with fraud         1.216492
Credit increase                       1.134300
Identification and authentication     1.037636
Recovery                              0.953806
Late fee waiver                       0.822463
Replacement card                      0.769216
menu upfront                          0.765120
menu eService                         0.527829
Rewards                               0.479224
Get account number                    0.366996
Payment address                       0.347881
Refer customer to store               0.310199
eService Login                        0.307741
Payment sent                          0.292723
eService Online Payment               0.269785
Close account                         0.223092
Proactive Income                      0.215446
Missing payment                       0.208346
Decline Sale                          0.205070
PIN Request                           0.202885
Statement reprint                     0.184590
Cancel payment                        0.177763
Summary payment                       0.153734
eService Password                     0.136804
eService Assistance                   0.125882
Return Payment                        0.123697
Change due date                       0.107040
Fraud Block Removal                   0.087380
Deceased Notification                 0.075092
Credit balance refund                 0.069904
eService Registration                 0.049970
Balance letter                        0.041779
Membership club                       0.032221
Minimum Payment disambiguation        0.026760
Global router                         0.019660
Fraud -instalink                      0.019114
Name: count, dtype: float64

In [17]:
dfCallGroup = copy.groupby("Reason Description").agg('count').reset_index()
dfCallGroup

,Reason Description,timestamp_call_key,retailer_code,serial,reason,mos,resolved,no_of_accounts_with_syf_13_march,account_balance_13_march,delinquency_history_13_march,...,auto_pay_enrolled_status_13_march,no_of_accounts_with_syf_18_march,account_balance_18_march,delinquency_history_18_march,account_open_date_18_march,account_status_18_march,card_activation_status_18_march,eservice_ind_18_march,ebill_enrolled_status_18_march,auto_pay_enrolled_status_18_march
0,Account Summary,566351,566351,566351,566351,566351,566351,563952,524289,566351,...,566351,563952,530300,566351,566351,35082,566351,566351,563801,566351
1,Account transactions,91404,91404,91404,91404,91404,91404,91317,86593,91404,...,91404,91317,86893,91404,91404,1479,91404,91404,91168,91404
2,Activation,54861,54861,54861,54861,54861,54861,54839,48146,54861,...,54861,54839,49488,54861,54861,1395,54861,54861,54629,54861
3,Address phone change,6729,6729,6729,6729,6729,6729,6727,6019,6729,...,6729,6727,6156,6729,6729,590,6729,6729,6685,6729
4,Balance letter,174,174,174,174,174,174,174,159,174,...,174,174,167,174,174,17,174,174,172,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,menu payment,7614,7614,7614,7614,7614,7614,7530,7103,7614,...,7614,7530,7215,7614,7614,580,7614,7614,7541,7614
67,menu upfront,4028,4028,4028,4028,4028,4028,4028,3874,4028,...,4028,4028,3889,4028,4028,569,4028,4028,4007,4028
68,more menu options,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,0,1,1,1,1
69,online lockout,58,58,58,58,58,58,58,58,58,...,58,58,58,58,58,4,58,58,58,58
70,pre transfer menu,5,5,5,5,5,5,5,3,5,...,5,5,4,5,5,0,5,5,5,5

In [18]:
dfFloorGroup = cFloor.groupby("Reason Description").agg("count").reset_index()
dfFloorGroup

,Reason Description,timestamp_call_key,retailer_code,serial,reason,mos,resolved,no_of_accounts_with_syf_13_march,account_balance_13_march,delinquency_history_13_march,...,auto_pay_enrolled_status_13_march,no_of_accounts_with_syf_18_march,account_balance_18_march,delinquency_history_18_march,account_open_date_18_march,account_status_18_march,card_activation_status_18_march,eservice_ind_18_march,ebill_enrolled_status_18_march,auto_pay_enrolled_status_18_march
0,Account Summary,158394,158394,158394,158394,158394,158394,156531,145368,158394,...,158394,156531,148135,158394,158394,18470,158394,158394,157158,158394
1,Account transactions,8687,8687,8687,8687,8687,8687,8642,8067,8687,...,8687,8642,8161,8687,8687,780,8687,8687,8633,8687
2,Activation,15089,15089,15089,15089,15089,15089,15070,12850,15089,...,15089,15070,13354,15089,15089,1073,15089,15089,14985,15089
3,Address phone change,4541,4541,4541,4541,4541,4541,4539,3961,4541,...,4541,4539,4093,4541,4541,448,4541,4541,4505,4541
4,Balance letter,153,153,153,153,153,153,153,140,153,...,153,153,147,153,153,16,153,153,152,153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,menu payment,5426,5426,5426,5426,5426,5426,5346,5092,5426,...,5426,5346,5173,5426,5426,419,5426,5426,5367,5426
64,menu upfront,2802,2802,2802,2802,2802,2802,2802,2690,2802,...,2802,2802,2704,2802,2802,399,2802,2802,2785,2802
65,more menu options,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,0,1,1,1,1
66,online lockout,57,57,57,57,57,57,57,57,57,...,57,57,57,57,57,4,57,57,57,57
67,pre transfer menu,3,3,3,3,3,3,3,1,3,...,3,3,2,3,3,0,3,3,3,3

In [19]:
dfCallCount = pd.DataFrame({"Reason Description":dfCallGroup["Reason Description"], "Calls":dfCallGroup["reason"]})
dfCallCount

      Reason Description   Calls
0        Account Summary  566351
1   Account transactions   91404
2             Activation   54861
3   Address phone change    6729
4         Balance letter     174
..                   ...     ...
66          menu payment    7614
67          menu upfront    4028
68     more menu options       1
69        online lockout      58
70     pre transfer menu       5

[71 rows x 2 columns]

In [20]:
dfFloorCount = pd.DataFrame({"Reason Description":dfFloorGroup["Reason Description"], "Floors":dfFloorGroup["reason"]})
dfFloorCount

      Reason Description  Floors
0        Account Summary  158394
1   Account transactions    8687
2             Activation   15089
3   Address phone change    4541
4         Balance letter     153
..                   ...     ...
63          menu payment    5426
64          menu upfront    2802
65     more menu options       1
66        online lockout      57
67     pre transfer menu       3

[68 rows x 2 columns]

In [21]:
dfToFloorPercentage = pd.merge(dfCallCount, dfFloorCount, on='Reason Description')
dfToFloorPercentage

      Reason Description   Calls  Floors
0        Account Summary  566351  158394
1   Account transactions   91404    8687
2             Activation   54861   15089
3   Address phone change    6729    4541
4         Balance letter     174     153
..                   ...     ...     ...
63          menu payment    7614    5426
64          menu upfront    4028    2802
65     more menu options       1       1
66        online lockout      58      57
67     pre transfer menu       5       3

[68 rows x 3 columns]

In [22]:
dfToFloorPercentage["Percent to Floor"] = dfToFloorPercentage["Floors"].div(dfToFloorPercentage["Calls"])*100
dfToFloorPercentage

      Reason Description   Calls  Floors  Percent to Floor
0        Account Summary  566351  158394         27.967462
1   Account transactions   91404    8687          9.503960
2             Activation   54861   15089         27.504056
3   Address phone change    6729    4541         67.484024
4         Balance letter     174     153         87.931034
..                   ...     ...     ...               ...
63          menu payment    7614    5426         71.263462
64          menu upfront    4028    2802         69.563059
65     more menu options       1       1        100.000000
66        online lockout      58      57         98.275862
67     pre transfer menu       5       3         60.000000

[68 rows x 4 columns]

In [23]:
dfTop50Floor = dfToFloorPercentage.nlargest(n=50, columns="Floors").reset_index()
dfTop50Floor

    index                 Reason Description   Calls  Floors  Percent to Floor
0       0                    Account Summary  566351  158394         27.967462
1      32                     PBP Predictive  678314   33562          4.947856
2       5                CIT Change in Terms   23796   23082         96.999496
3      33                        PBP Request  221583   18309          8.262818
4       2                         Activation   54861   15089         27.504056
5      44                     Request waiver   14296   13248         92.669278
6      18                       Fraud detect   13007   12474         95.902207
7      43                 Report lost stolen   13771    9482         68.854840
8       1               Account transactions   91404    8687          9.503960
9      24                          Live chat   10076    7582         75.248114
10     15                           Disputes    6930    6828         98.528139
11     63                       menu payment    7614    5426         71.263462
12     39                      Promo balance    7125    4860         68.210526
13      3               Address phone change    6729    4541         67.484024
14     61      manage fraud - L/S with fraud    4755    4455         93.690852
15     12                    Credit increase    8911    4154         46.616541
16     22  Identification and authentication    7617    3800         49.888408
17     40                           Recovery    3756    3493         92.997870
18     23                    Late fee waiver    4910    3012         61.344196
19     42                   Replacement card    4185    2817         67.311828
20     64                       menu upfront    4028    2802         69.563059
21     62                      menu eService    2150    1933         89.906977
22     46                            Rewards    2162    1755         81.174838
23     19                 Get account number    2042    1344         65.817826
24     35                    Payment address    2608    1274         48.849693
25     41            Refer customer to store    2071    1136         54.852728
26     56                     eService Login    1642    1127         68.635810
27     37                       Payment sent    1772    1072         60.496614
28     57            eService Online Payment    1192     988         82.885906
29     10                      Close account    5920     817         13.800676
30     38                   Proactive Income    3447     789         22.889469
31     28                    Missing payment    1503     763         50.765136
32     14                       Decline Sale    1524     751         49.278215
33     34                        PIN Request    2443     743         30.413426
34     47                  Statement reprint    1070     676         63.177570
35      6                    Cancel payment      743     651         87.617766
36     49                    Summary payment    2694     563         20.898293
37     58                  eService Password     769     501         65.149545
38     54                eService Assistance     697     461         66.140603
39     45                    Return Payment      873     453         51.890034
40      8                    Change due date     477     392         82.180294
41     17                Fraud Block Removal    1273     320         25.137471
42     13              Deceased Notification     282     275         97.517730
43     11              Credit balance refund    3694     256          6.930157
44     59              eService Registration     362     183         50.552486
45      4                     Balance letter     174     153         87.931034
46     26                    Membership club     215     118         54.883721
47     27     Minimum Payment disambiguation     178      98         55.056180
48     20                      Global router      72      72        100.000000
49     16                  Fraud -instalink      174      70         40.229885

In [24]:
dfTop50Percent = dfToFloorPercentage.nlargest(n=50, columns="Percent to Floor")
dfTop50Percent

                Reason Description  Calls  Floors  Percent to Floor
20                   Global router     72      72        100.000000
21                 HRT - Instalink      1       1        100.000000
30                            Null      2       2        100.000000
50                        Transfer      1       1        100.000000
65               more menu options      1       1        100.000000
15                        Disputes   6930    6828         98.528139
66                  online lockout     58      57         98.275862
13           Deceased Notification    282     275         97.517730
9                     Claim Status     71      69         97.183099
5              CIT Change in Terms  23796   23082         96.999496
48           StoneBridge insurance     28      27         96.428571
18                    Fraud detect  13007   12474         95.902207
61   manage fraud - L/S with fraud   4755    4455         93.690852
36              Payment allocation     43      40         93.023256
40                        Recovery   3756    3493         92.997870
44                  Request waiver  14296   13248         92.669278
62                   menu eService   2150    1933         89.906977
4                   Balance letter    174     153         87.931034
6                  Cancel payment     743     651         87.617766
53                   Vague address     82      68         82.926829
57         eService Online Payment   1192     988         82.885906
8                  Change due date    477     392         82.180294
46                         Rewards   2162    1755         81.174838
24                       Live chat  10076    7582         75.248114
52          UNABLE TO PARSE REASON     18      13         72.222222
63                    menu payment   7614    5426         71.263462
64                    menu upfront   4028    2802         69.563059
7                      Cash access     87      60         68.965517
43              Report lost stolen  13771    9482         68.854840
56                  eService Login   1642    1127         68.635810
39                   Promo balance   7125    4860         68.210526
3             Address phone change   6729    4541         67.484024
42                Replacement card   4185    2817         67.311828
25                  Membership Fee     12       8         66.666667
60               eService Security      9       6         66.666667
54             eService Assistance    697     461         66.140603
19              Get account number   2042    1344         65.817826
58               eService Password    769     501         65.149545
47               Statement reprint   1070     676         63.177570
23                 Late fee waiver   4910    3012         61.344196
37                    Payment sent   1772    1072         60.496614
67               pre transfer menu      5       3         60.000000
29       Non account specific info     16       9         56.250000
27  Minimum Payment disambiguation    178      98         55.056180
26                 Membership club    215     118         54.883721
41         Refer customer to store   2071    1136         54.852728
31                OB IB Prediction     13       7         53.846154
45                 Return Payment     873     453         51.890034
28                 Missing payment   1503     763         50.765136
59           eService Registration    362     183         50.552486

In [25]:
dfOverview = pd.merge(dfTop50Percent, dfTop50Floor, on='Reason Description').sort_values(by="Floors_x", ascending=False).reset_index()
dfOverview[["Reason Description", "Calls_x", "Floors_x", "Percent to Floor_x"]]

                Reason Description  Calls_x  Floors_x  Percent to Floor_x
0              CIT Change in Terms    23796     23082           96.999496
1                   Request waiver    14296     13248           92.669278
2                     Fraud detect    13007     12474           95.902207
3               Report lost stolen    13771      9482           68.854840
4                        Live chat    10076      7582           75.248114
5                         Disputes     6930      6828           98.528139
6                     menu payment     7614      5426           71.263462
7                    Promo balance     7125      4860           68.210526
8             Address phone change     6729      4541           67.484024
9    manage fraud - L/S with fraud     4755      4455           93.690852
10                        Recovery     3756      3493           92.997870
11                 Late fee waiver     4910      3012           61.344196
12                Replacement card     4185      2817           67.311828
13                    menu upfront     4028      2802           69.563059
14                   menu eService     2150      1933           89.906977
15                         Rewards     2162      1755           81.174838
16              Get account number     2042      1344           65.817826
17         Refer customer to store     2071      1136           54.852728
18                  eService Login     1642      1127           68.635810
19                    Payment sent     1772      1072           60.496614
20         eService Online Payment     1192       988           82.885906
21                 Missing payment     1503       763           50.765136
22               Statement reprint     1070       676           63.177570
23                 Cancel payment       743       651           87.617766
24               eService Password      769       501           65.149545
25             eService Assistance      697       461           66.140603
26                 Return Payment       873       453           51.890034
27                 Change due date      477       392           82.180294
28           Deceased Notification      282       275           97.517730
29           eService Registration      362       183           50.552486
30                  Balance letter      174       153           87.931034
31                 Membership club      215       118           54.883721
32  Minimum Payment disambiguation      178        98           55.056180
33                   Global router       72        72          100.000000

In [29]:
copy[0:50]

,timestamp_call_key,retailer_code,serial,reason,mos,resolved,no_of_accounts_with_syf_13_march,account_balance_13_march,delinquency_history_13_march,account_open_date_13_march,...,no_of_accounts_with_syf_18_march,account_balance_18_march,delinquency_history_18_march,account_open_date_18_march,account_status_18_march,card_activation_status_18_march,eservice_ind_18_march,ebill_enrolled_status_18_march,auto_pay_enrolled_status_18_march,Reason Description
0,240315173250 DAL1OA3M,D,10010009499,PP,IA PP TR,resolved,1.0,NaN,[00],5/19/2013,...,1.0,NaN,[00],5/19/2013,NaN,0,1,E,0,PBP Predictive
1,240315124742 DAL15XHK,E,10006021998,BA,IA BA TS nl TR,floor,2.0,143.28,[00],9/22/2003,...,2.0,143.28,[00],9/22/2003,NaN,0,1,E,0,Account Summary
2,240317114237 DAL3BLK6,J,10016007830,PT,IA AA BA MR nl PT TR,resolved,12.0,0.00,[00],9/4/2017,...,12.0,0.00,[00],9/4/2017,NaN,8,0,,0,PBP Request
3,240314120849 PHX6PL4U,E,10008003199,BA,IA BA,resolved,2.0,44.98,[00],2/7/2024,...,2.0,-6.32,[00],2/7/2024,NaN,0,0,L,0,Account Summary
4,240314145902 DAL68RYS,I,10013002037,BA,IA BA TS nl mm TR,floor,6.0,7.00,[00],1/2/2022,...,6.0,7.00,[00],1/2/2022,NaN,0,1,,0,Account Summary
5,240314151323 PHX4I30S,I,10013002037,PS,IA BA TS nl PS nl mt RS TR,floor,6.0,7.00,[00],1/2/2022,...,6.0,7.00,[00],1/2/2022,NaN,0,1,,0,Payment sent
6,240316012428 PHX43JOI,E,10006032399,BA,IA BA,resolved,3.0,NaN,[02],9/26/2021,...,3.0,NaN,[02],9/26/2021,NaN,0,0,L,0,Account Summary
7,240316171347 PHX4I164,B,10002094529,BA,IA BA,resolved,6.0,0.00,[00],9/13/2020,...,6.0,0.00,[00],9/13/2020,NaN,0,0,,0,Account Summary
8,240316171945 DAL16OYM,B,10002094529,BA,IA IA IA BA,resolved,6.0,0.00,[00],9/13/2020,...,6.0,0.00,[00],9/13/2020,NaN,0,0,,0,Account Summary
9,240314104010 PHX24CE2,D,10004003523,BA,IA PP BA MR nl,resolved,4.0,373.68,[00],3/12/2023,...,4.0,373.68,[00],3/12/2023,NaN,0,0,,0,Account Summary
10,240317234904 DAL5X9Y0,B,10007034394,eL,IA BA TS nl eL TR,floor,2.0,NaN,[00],3/3/2024,...,2.0,NaN,[00],3/3/2024,NaN,0,0,,0,eService Login
11,240314122855 PHX7XSQO,E,10008003472,PT,IA AA BA MR nl PT TR,resolved,6.0,2842.61,[00],2/22/2015,...,6.0,2842.61,[00],2/22/2015,NaN,8,0,L,0,PBP Request
12,240314190516 DAL2W0TV,J,10021000655,PP,IA PP TR,resolved,4.0,669.33,[00],1/24/2022,...,4.0,669.33,[00],1/24/2022,NaN,0,0,,0,PBP Predictive
13,240317180714 PHX6PUE6,A,10001141323,PP,IA PP TR,resolved,4.0,3023.22,[00],11/18/2007,...,4.0,3023.22,[00],11/18/2007,NaN,0,0,L,0,PBP Predictive
14,240317115830 PHX3XB97,D,10004051348,PP,IA PP TR,resolved,1.0,963.27,[00],9/14/2020,...,1.0,963.27,[00],9/14/2020,NaN,0,1,L,0,PBP Predictive
15,240314013642 PHX15P0A,A,10001000726,BA,IA BA TS,resolved,5.0,0.00,[00],1/11/2024,...,5.0,0.00,[00],1/11/2024,NaN,0,1,E,0,Account Summary
16,240314140920 PHX1E0UN,A,10001022870,BA,IA PP BA TS nl,resolved,12.0,3648.56,[00],6/21/2015,...,12.0,3648.56,[00],6/21/2015,NaN,0,1,E,0,Account Summary
17,240314081235 DAL1ROPP,I,10013000316,BA,IA AA BA MR nl TR,floor,2.0,8.37,[00],2/5/2024,...,2.0,0.00,[00],2/5/2024,F,7,0,,0,Account Summary
18,240314081822 DAL1C80T,I,10013000316,BA,IA AA BA MR nl TR,floor,2.0,8.37,[00],2/5/2024,...,2.0,0.00,[00],2/5/2024,F,7,0,,0,Account Summary
19,240315134304 PHX3NVRH,B,10002053669,PT,IA PP BA TS nl AT nl PT TR,resolved,14.0,697.75,[00],6/13/2016,...,14.0,697.75,[00],6/13/2016,NaN,0,0,,0,PBP Request
20,240314114650 DAL6K9K1,B,10002010726,PP,IA PP TR,resolved,3.0,10.19,[03],8/26/2021,...,3.0,10.19,[03],8/26/2021,NaN,0,1,,0,PBP Predictive
21,240314115040 PHX4BTO7,B,10002010726,PP,IA PP TR,resolved,3.0,10.19,[03],8/26/2021,...,3.0,10.19,[03],8/26/2021,NaN,0,1,,0,PBP Predictive
22,240315161527 DAL5NC9N,B,10007016674,BA,IA BA,resolved,5.0,88.32,[00],9/26/2014,...,5.0,88.32,[00],9/26/2014,NaN,0,0,,0,Account Summary
23,240315163219 DAL2MQGX,A,10001078402,BA,IA PI BA MR nl nl mt nl mm mo TR,floor,4.0,0.00,[00],4/19/2023,...,4.0,0.00,[00],4/19/2023,NaN,0,0,L,0,Account Summary
24,240317133526 PHX2MBCI,B,10002109940,PP,IA PP TR,resolved,2.0,5.52,[00],11/2/2017,...,2.0,5.52,[00],11/2/2017,NaN,0,0,,0,PBP Predictive
25,240314134813 DAL6DHO5,B,10002016264,PP,IA IA PP TR,resolved,2.0,948.01,[00],12/18/2016,...,2.0,948.01,[00],12/18/2016,NaN,0,1,,0,PBP Predictive
26,240315122737 DAL1YTSL,B,10015004076,PP,IA PP TR,resolved,2.0,1658.44,[00],4/25/2008,...,2.0,1658.44,[00],4/25/2008,NaN,0,1,,0,PBP Predictive
27,240316091115 PHX6SMWA,C,10003068607,PP,mn IA PP TR,resolved,2.0,NaN,[00],4/7/2022,...,2.0,NaN,[00],4/7/2022,NaN,0,0,L,0,PBP Predictive
28,240315151547 DAL6OU0T,A,10001073587,PP,IA PP TR,resolved,8.0,3802.95,[00],7/20/2015,...,8.0,3802.95,[00],7/20/2015,NaN,0,1,L,0,PBP Predictive
29,240316142247 DAL7JJUX,A,10001073587,BA,IA PP BA TS nl mt RS TR,floor,8.0,3802.95,[00],7/20/2015,...,8.0,3802.95,[00],7/20/2015,NaN,0,1,L,0,Account Summary
30,240315113916 DAL3W7CH,C,10026000894,PS,mn IA PP BA TS mm mo mm mp PS,resolved,1.0,22.13,[00],10/31/2023,...,1.0,22.13,[00],10/31/2023,NaN,0,1,L,0,Payment sent
31,240314123738 DAL5SYPK,C,10003012742,BA,mn IA BA,resolved,7.0,0.00,[00],10/6/2019,...,7.0,0.00,[00],10/6/2019,NaN,0,1,L,0,Account Summary
32,240314145958 PHX53ASI,E,10006008352,PP,IA PP TR,resolved,1.0,872.02,[00],8/16/2022,...,1.0,872.02,[00],8/16/2022,NaN,0,0,L,0,PBP Predictive
33,240317164419 DAL7S9AI,D,10005051168,PT,IA BA TS nl PT TR,resolved,6.0,594.62,[00],9/24/2019,...,6.0,594.62,[00],9/24/2019,NaN,0,1,E,0,PBP Request
34,240316142441 PHX2N3TA,E,10008023480,PP,IA PP TR,resolved,17.0,93.17,[00],1/8/2023,...,17.0,93.17,[00],1/8/2023,NaN,0,0,L,0,PBP Predictive
35,240315173309 PHX2FWYV,A,10001081909,PT,IA BA MR nl PT TR,resolved,8.0,831.61,[00],4/9/2021,...,8.0,2803.92,[00],4/9/2021,NaN,0,0,L,0,PBP Request
36,240315103523 PHX5XMVH,A,10001055833,BA,IA PP BA,resolved,5.0,5998.05,[00],11/4/2018,...,5.0,5998.05,[00],11/4/2018,NaN,0,0,L,0,Account Summary
37,240317151813 DAL3RB0R,J,10021002840,BA,IA PI BA MR mm mo mt RS TR,floor,4.0,191.39,[20],6/7/2023,...,4.0,191.39,[20],6/7/2023,NaN,0,0,,0,Account Summary
38,240315161642 PHX6OACR,E,10006026419,AP,IA PI BA MR nl AP HI TR,floor,3.0,62.19,[00],3/30/2002,...,3.0,62.19,[00],3/30/2002,NaN,0,0,L,0,Address phone change
39,240314140223 PHX2344A,B,10002016864,BA,IA IA PP BA,resolved,10.0,194.85,[00],8/4/2013,...,10.0,194.85,[00],8/4/2013,NaN,0,1,E,0,Account Summary
40,240315134622 DAL6DHIV,I,10013005305,PT,IA BA MR nl PT TR,resolved,5.0,0.00,[00],12/29/2023,...,5.0,0.00,[00],12/29/2023,NaN,0,0,,0,PBP Request
41,240315135410 PHX48NQA,I,10013005305,BA,IA BA MR nl mm,resolved,5.0,0.00,[00],12/29/2023,...,5.0,0.00,[00],12/29/2023,NaN,0,0,,0,Account Summary
42,240315155048 DAL28IST,I,10013005305,FD,IA FI TR,floor,5.0,0.00,[00],12/29/2023,...,5.0,0.00,[00],12/29/2023,NaN,0,0,,0,Fraud detect
43,240315153900 PHX4E7GA,E,10008015842,BA,IA IA BA,resolved,11.0,1948.22,[20],9/4/2022,...,11.0,1948.22,[20],9/4/2022,NaN,0,1,E,0,Account Summary
44,240316120409 PHX2755J,C,10003072672,DR,mn IA DR TR,floor,3.0,NaN,[00],12/6/2023,...,3.0,NaN,[00],12/6/2023,NaN,0,1,E,0,Decline Sale
45,240316050225 DAL29365,C,10003067004,AT,mn IA BA TS nl AT,resolved,4.0,232.98,[00],10/19/2023,...,4.0,232.98,[00],10/19/2023,NaN,0,1,E,1,Account transactions
46,240316050625 PHX4D90K,C,10003067004,BA,mn IA BA TS nl,resolved,4.0,232.98,[00],10/19/2023,...,4.0,232.98,[00],10/19/2023,NaN,0,1,E,1,Account Summary
47,240317065915 PHX6IC0T,H,10012011503,BA,IA BA nl,resolved,5.0,3210.84,[00],7/31/2023,...,5.0,3177.84,[00],7/31/2023,NaN,0,1,E,0,Account Summary
48,240315191417 PHX5BYHL,A,10001086400,BA,IA IA IA BA,resolved,3.0,2499.49,[00],11/22/2021,...,3.0,2499.49,[00],11/22/2021,NaN,0,0,L,0,Account Summary
49,240316182249 DAL679NN,A,10001086400,BA,IA IA IA BA,resolved,3.0,2499.49,[00],11/22/2021,...,3.0,2499.49,[00],11/22/2021,NaN,0,0,L,0,Account Summary